.PHONY: ping
ping:
	sh tool.sh ping

.PHONY: ifup
ifup:
	sh tool.sh ifup

.PHONY: ifdown
ifdown:
	sh tool.sh ifdown

.PHONY: run-cli
run-cli: 
	sh tool.sh runcli 

.PHONY: stop-cli
stop-cli:
	sh tool.sh stopcli 

.PHONY: run-srv
run-srv: 
	sh tool.sh runsrv
